name: Python build

on:
  workflow_dispatch:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name:  Set up python 
        uses: actions/setup-python@v2
        with:
          python-version:  '3.9'
      - name: Display Python version
        run: python -c "import sys; print({sys.version})"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install runestone
      - name: Build project
        run: |
          cd ./myassignments
          runestone build
          python -c "import sys; print('All done')"
